name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release - CI
    runs-on: ${{ (github.event.act) && 'ubuntu-latest' || fromJSON('[ "self-hosted", "Linux", "X64" ]') }}
    permissions:
      contents: write # to be able to publish a GitHub release
      pull-requests: write # to be able to comment on released pull requests
      issues: write # to be able to comment on released issues
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: |
          npm install -g pnpm
          npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: pnpm run release:all
